"""initial_tables

Revision ID: c69431cfe855
Revises: 
Create Date: 2026-05-13 23:47:36.728960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c69431cfe855'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('screening_date', sa.DateTime(), nullable=False),
    sa.Column('total_screened', sa.Integer(), nullable=False),
    sa.Column('passed_filters', sa.Integer(), nullable=False),
    sa.Column('safe_zone', sa.Integer(), nullable=False),
    sa.Column('grey_zone', sa.Integer(), nullable=False),
    sa.Column('distress_zone', sa.Integer(), nullable=False),
    sa.Column('top_opportunities_json', sa.Text(), nullable=True),
    sa.Column('errors_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_summaries_screening_date'), 'daily_summaries', ['screening_date'], unique=False)
    op.create_table('screening_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('screening_date', sa.DateTime(), nullable=False),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.Column('f_score', sa.Integer(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('pb_ratio', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('current_ratio', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('fair_value_dcf', sa.Float(), nullable=True),
    sa.Column('safety_margin', sa.Float(), nullable=True),
    sa.Column('upside_potential', sa.Float(), nullable=True),
    sa.Column('quality_ratio', sa.Float(), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('passes_filters', sa.Boolean(), nullable=False),
    sa.Column('financials_json', sa.Text(), nullable=True),
    sa.Column('valuation_json', sa.Text(), nullable=True),
    sa.Column('downside_risks_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_results_passes_filters'), 'screening_results', ['passes_filters'], unique=False)
    op.create_index(op.f('ix_screening_results_screening_date'), 'screening_results', ['screening_date'], unique=False)
    op.create_index(op.f('ix_screening_results_ticker'), 'screening_results', ['ticker'], unique=False)
    op.create_index('ix_sr_passes_filters', 'screening_results', ['passes_filters'], unique=False)
    op.create_index('ix_sr_ticker_date', 'screening_results', ['ticker', 'screening_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sr_ticker_date', table_name='screening_results')
    op.drop_index('ix_sr_passes_filters', table_name='screening_results')
    op.drop_index(op.f('ix_screening_results_ticker'), table_name='screening_results')
    op.drop_index(op.f('ix_screening_results_screening_date'), table_name='screening_results')
    op.drop_index(op.f('ix_screening_results_passes_filters'), table_name='screening_results')
    op.drop_table('screening_results')
    op.drop_index(op.f('ix_daily_summaries_screening_date'), table_name='daily_summaries')
    op.drop_table('daily_summaries')
    # ### end Alembic commands ###
